### ISSUE TITLE
pypi tarball missing test files

### ISSUE THREAD

**Issue by nieder** [reubano/csv2ofx#105]
The directory `data/test` is empty in the tarball downloaded from pypi. This means that tests fail when trying to build/test/install csv2ofx.

**Comment by jaraco** [comment]
This was fixed in #127. Let me know if you don't find it fixed in the latest releases.

**Comment by nieder** [comment]
When building 0.31.0, still don't have `data/test` in the PyPi tarball:
```
Script result: /sw/build.build/csv2ofx-py310-0.31.0-1/csv2ofx-0.31.0/bin/csv2ofx -oq /sw/build.build/csv2ofx-py310-0.31.0-1/csv2ofx-0.31.0/data/test/default.csv
  return code: 1
-- stderr: --------------------
Traceback (most recent call last):
  File "/sw/build.build/csv2ofx-py310-0.31.0-1/csv2ofx-0.31.0/bin/csv2ofx", line 16, in <module>
    run()
  File "/sw/build.build/csv2ofx-py310-0.31.0-1/csv2ofx-0.31.0/csv2ofx/main.py", line 237, in run
    source = open(args.source, encoding=args.encoding) if args.source else stdin
FileNotFoundError: [Errno 2] No such file or directory: '/sw/build.build/csv2ofx-py310-0.31.0-1/csv2ofx-0.31.0/data/test/default.csv'
```

I tried building 0.32.0, but my setuptools is too old:
```
running egg_info
creating UNKNOWN.egg-info
writing UNKNOWN.egg-info/PKG-INFO
writing dependency_links to UNKNOWN.egg-info/dependency_links.txt
writing top-level names to UNKNOWN.egg-info/top_level.txt
writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'
reading manifest file 'UNKNOWN.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
```
However, the 0.32.0 PyPi tarball also doesn't have a `data/test` directory.
Building/testing from the github tarball passes all tests.

**Comment by jaraco** [comment]
Thanks for the report. When I checked it, I was only looking for `tests/test.py`, which is there. It seems the problem is there are other files missing.

```
 csv2ofx main 🐚 git checkout v0.31.0
HEAD is now at 949273f Merge pull request #132 from reubano/feature/release
 csv2ofx 949273f 🐚 pyproject-build -s .
* Creating isolated environment: venv+pip...
* Installing packages in isolated environment:
  - pkutils>=3.0.0,<4.0.0
  - setuptools>=42.0.2
* Getting build dependencies for sdist...
* Installing packages in isolated environment:
  - pkutils>=3.0.0,<4.0.0
* Building sdist...
/private/var/folders/f2/2plv6q2n7l932m2x004jlw340000gn/T/build-env-g51b2ag0/lib/python3.12/site-packages/setuptools/_distutils/dist.py:270: UserWarning: Unknown distribution option: 'test_suite'
  warnings.warn(msg)
/private/var/folders/f2/2plv6q2n7l932m2x004jlw340000gn/T/build-env-g51b2ag0/lib/python3.12/site-packages/setuptools/_distutils/dist.py:270: UserWarning: Unknown distribution option: 'tests_require'
  warnings.warn(msg)
running sdist
running egg_info
creating csv2ofx.egg-info
writing csv2ofx.egg-info/PKG-INFO
writing dependency_links to csv2ofx.egg-info/dependency_links.txt
writing requirements to csv2ofx.egg-info/requires.txt
writing top-level names to csv2ofx.egg-info/top_level.txt
writing manifest file 'csv2ofx.egg-info/SOURCES.txt'
reading manifest file 'csv2ofx.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'csv2ofx/data'
warning: no files found matching '*' under directory 'examples'
warning: no files found matching '*.rst'
adding license file 'LICENSE'
writing manifest file 'csv2ofx.egg-info/SOURCES.txt'
running check
creating csv2ofx-0.31.0
creating csv2ofx-0.31.0/bin
creating csv2ofx-0.31.0/csv2ofx
creating csv2ofx-0.31.0/csv2ofx.egg-info
creating csv2ofx-0.31.0/csv2ofx/mappings
creating csv2ofx-0.31.0/docs
creating csv2ofx-0.31.0/docs/QIF Specification_files
creating csv2ofx-0.31.0/helpers
creating csv2ofx-0.31.0/tests
copying files to csv2ofx-0.31.0...
copying LICENSE -> csv2ofx-0.31.0
copying MANIFEST.in -> csv2ofx-0.31.0
copying README.md -> csv2ofx-0.31.0
copying dev-requirements.txt -> csv2ofx-0.31.0
copying pyproject.toml -> csv2ofx-0.31.0
copying requirements.txt -> csv2ofx-0.31.0
copying setup.cfg -> csv2ofx-0.31.0
copying setup.py -> csv2ofx-0.31.0
copying bin/csv2ofx -> csv2ofx-0.31.0/bin
copying csv2ofx/__init__.py -> csv2ofx-0.31.0/csv2ofx
copying csv2ofx/main.py -> csv2ofx-0.31.0/csv2ofx
copying csv2ofx/ofx.py -> csv2ofx-0.31.0/csv2ofx
copying csv2ofx/qif.py -> csv2ofx-0.31.0/csv2ofx
copying csv2ofx/utils.py -> csv2ofx-0.31.0/csv2ofx
copying csv2ofx.egg-info/PKG-INFO -> csv2ofx-0.31.0/csv2ofx.egg-info
copying csv2ofx.egg-info/SOURCES.txt -> csv2ofx-0.31.0/csv2ofx.egg-info
copying csv2ofx.egg-info/dependency_links.txt -> csv2ofx-0.31.0/csv2ofx.egg-info
copying csv2ofx.egg-info/not-zip-safe -> csv2ofx-0.31.0/csv2ofx.egg-info
copying csv2ofx.egg-info/requires.txt -> csv2ofx-0.31.0/csv2ofx.egg-info
copying csv2ofx.egg-info/top_level.txt -> csv2ofx-0.31.0/csv2ofx.egg-info
copying csv2ofx/mappings/__init__.py -> csv2ofx-0.31.0/csv2ofx/mappings
copying csv2ofx/mappings/abnamro.py -> csv2ofx-0.31.0/csv2ofx/mappings
copying csv2ofx/mappings/amazon.py -> csv2ofx-0.31.0/csv2ofx/mappings
copying csv2ofx/mappings/boursorama.py -> csv2ofx-0.31.0/csv2ofx/mappings
copying csv2ofx/mappings/capitalone.py -> csv2ofx-0.31.0/csv2ofx/mappings
copying csv2ofx/mappings/creditunion.py -> csv2ofx-0.31.0/csv2ofx/mappings
copying csv2ofx/mappings/custom.py -> csv2ofx-0.31.0/csv2ofx/mappings
copying csv2ofx/mappings/default.py -> csv2ofx-0.31.0/csv2ofx/mappings
copying csv2ofx/mappings/eqbank.py -> csv2ofx-0.31.0/csv2ofx/mappings
copying csv2ofx/mappings/exim.py -> csv2ofx-0.31.0/csv2ofx/mappings
copying csv2ofx/mappings/gls.py -> csv2ofx-0.31.0/csv2ofx/mappings
copying csv2ofx/mappings/ingdirect.py -> csv2ofx-0.31.0/csv2ofx/mappings
copying csv2ofx/mappings/ingesp.py -> csv2ofx-0.31.0/csv2ofx/mappings
copying csv2ofx/mappings/mdb.py -> csv2ofx-0.31.0/csv2ofx/mappings
copying csv2ofx/mappings/mint.py -> csv2ofx-0.31.0/csv2ofx/mappings
copying csv2ofx/mappings/mint_extra.py -> csv2ofx-0.31.0/csv2ofx/mappings
copying csv2ofx/mappings/mint_headerless.py -> csv2ofx-0.31.0/csv2ofx/mappings
copying csv2ofx/mappings/mintapi.py -> csv2ofx-0.31.0/csv2ofx/mappings
copying csv2ofx/mappings/msmoneyreport.py -> csv2ofx-0.31.0/csv2ofx/mappings
copying csv2ofx/mappings/n26.py -> csv2ofx-0.31.0/csv2ofx/mappings
copying csv2ofx/mappings/outbank.py -> csv2ofx-0.31.0/csv2ofx/mappings
copying csv2ofx/mappings/pcmastercard.py -> csv2ofx-0.31.0/csv2ofx/mappings
copying csv2ofx/mappings/rabobank.py -> csv2ofx-0.31.0/csv2ofx/mappings
copying csv2ofx/mappings/schwabchecking.py -> csv2ofx-0.31.0/csv2ofx/mappings
copying csv2ofx/mappings/split_account.py -> csv2ofx-0.31.0/csv2ofx/mappings
copying csv2ofx/mappings/starling.py -> csv2ofx-0.31.0/csv2ofx/mappings
copying csv2ofx/mappings/stripe.py -> csv2ofx-0.31.0/csv2ofx/mappings
copying csv2ofx/mappings/ubs-ch-fr.py -> csv2ofx-0.31.0/csv2ofx/mappings
copying csv2ofx/mappings/ubs.py -> csv2ofx-0.31.0/csv2ofx/mappings
copying csv2ofx/mappings/xero.py -> csv2ofx-0.31.0/csv2ofx/mappings
copying csv2ofx/mappings/yodlee.py -> csv2ofx-0.31.0/csv2ofx/mappings
copying docs/OFX 2.1.1.pdf -> csv2ofx-0.31.0/docs
copying docs/OFXAudit.xls -> csv2ofx-0.31.0/docs
copying docs/OFX_Message_Support.doc -> csv2ofx-0.31.0/docs
copying docs/QIF Specification.html -> csv2ofx-0.31.0/docs
copying docs/qif-file-format.txt -> csv2ofx-0.31.0/docs
copying docs/QIF Specification_files/a.html -> csv2ofx-0.31.0/docs/QIF Specification_files
copying docs/QIF Specification_files/a_002.html -> csv2ofx-0.31.0/docs/QIF Specification_files
copying docs/QIF Specification_files/a_003.html -> csv2ofx-0.31.0/docs/QIF Specification_files
copying docs/QIF Specification_files/a_004.html -> csv2ofx-0.31.0/docs/QIF Specification_files
copying docs/QIF Specification_files/a_005.html -> csv2ofx-0.31.0/docs/QIF Specification_files
copying docs/QIF Specification_files/bootstrap.js -> csv2ofx-0.31.0/docs/QIF Specification_files
copying docs/QIF Specification_files/jquery.js -> csv2ofx-0.31.0/docs/QIF Specification_files
copying docs/QIF Specification_files/sitecss.css -> csv2ofx-0.31.0/docs/QIF Specification_files
copying helpers/check-stage -> csv2ofx-0.31.0/helpers
copying helpers/clean -> csv2ofx-0.31.0/helpers
copying helpers/srcdist -> csv2ofx-0.31.0/helpers
copying helpers/wheel -> csv2ofx-0.31.0/helpers
copying tests/test.py -> csv2ofx-0.31.0/tests
copying csv2ofx.egg-info/SOURCES.txt -> csv2ofx-0.31.0/csv2ofx.egg-info
Writing csv2ofx-0.31.0/setup.cfg
Creating tar archive
removing 'csv2ofx-0.31.0' (and everything under it)
Successfully built csv2ofx-0.31.0.tar.gz
```

Such is the hassle with using a manually-managed MANIFEST.in - if you get it wrong, you're missing files and you don't know it.

**Comment by jaraco** [comment]
I suspect v0.31.1 will fix the issue. Please give it a try after [the release](https://github.com/reubano/csv2ofx/actions/runs/13606062121) completes.

**Comment by nieder** [comment]
That did it. Thank you.
